#!/bin/bash

# Arch, nwg-look is available 
## Set GTK Themes, Icons, Cursor and Fonts

THEME='Nordic-standard-buttons-v40'
ICONS='Shiny-Dark-Icons'
FONT='Fantasque Sans Mono 17'
CURSOR='Bibata-Modern-Ice'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes() {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
