#!/bin/bash

## Files
CONFIG="$HOME/.config/hypr/wofi/config"
STYLE="$HOME/.config/hypr/wofi/style.css"
COLORS="$HOME/.config/hypr/wofi/colors"


DIR=$HOME/Pictures/wallpapers
PICS=($(ls ${DIR}))

RANDOMPIC=${PICS[ $RANDOM % ${#PICS[@]} ]}

SWWW_PARAMS="--transition-fps 30 --transition-type simple --transition-duration 3"

if [[ $(pidof swaybg) ]]; then
  pkill swaybg
fi

## Wofi Command
wofi_command="wofi --show dmenu \
			--prompt 'choose..'
			--conf ${CONFIG} --style ${STYLE} --color ${COLORS} \
			--width=25% --height=30% \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--define=matching=fuzzy"

menu(){
    for str in ${PICS[@]}; do
        printf "$str\n"
    done
    printf random
}

swww query || swww init

main() {
    choice=$(menu | ${wofi_command})
    if [ "$choice" = "random" ] 
    then
        swww img ${DIR}/${RANDOMPIC} $SWWW_PARAMS
        return
    fi
    swww img ${DIR}/${choice} $SWWW_PARAMS
    return
}


killall -f || main
